Update portal-rodent-trips.md
weecology/wiki pull request #27
Opened 2024-05-09 18:37 UTC by patdumandan

2024-05-09 20:00 UTC, ethanwhite requested changes
Looks really good @patdumandan! My one suggestion is that in the "Things to pack" section instead of using the `*` I'd probably have two subheadings. The first would be "Everyone" and include all the non-RA items and the second would the "RA" and include "Everything above" and then the RA-only items.

I've also added @skmorgane as a reviewer for a quick look on this one.

2024-05-10 13:13 UTC, patdumandan commented
I can do that, @ethanwhite! But, I was wondering if it would be better if this page just have all the details of the RA duties (including data entry/QA steps, where to get millet, gas, etc.) And then all of the things a volunteer needs to know (including what to pack) will be in the Portal volunteer guide?

Also, I was wondering if it would make sense to have another page for the Plant Census, which I can probably work on with @gmyenni.

2024-05-21 21:01 UTC, gmyenni commented
To the packing list or maybe a footnote on it, I would add an explanation of the tent situation. ie we have tents, you can bring your own as well but the desert tends to ruin them, you can sleep out but you'll contend with wind/scorpions/rodents bouncing off you. 
To the RA page, add an explanation of the GoalZero power setup - how to set it up in the ramada, how to set it up in the truck and why, where to order new accessories

2024-05-22 15:07 UTC, ethanwhite approved these changes

2024-05-22 17:17 UTC, gmyenni commented
Sweet! New RAs are going to be so prepared!
Few things:
* R stands for 'removed' not 'released'
* typo: PortalData -> DataCleaningScipts: DataCleaningScripts
* Add more about the red notebook: scan previous months' corrections to make sure you're not 'correcting' the same individuals back and forth
*  Maybe the data entry and cleaning steps should be subheaders under Post-trip Duties, so they're more prominent? ie You can move Download camera trap photos and Download PIT tags up to the main list, then have subsections each for Enter Data and QA data, with the rest of the lists under them

2024-05-22 22:00 UTC, gmyenni approved these changes

2024-06-05 17:18 UTC, gmyenni commented
Couple more nitpicky things:
* it's written like site maintenance happens on the summer plant trip, but it usually happens on the winter plant trip (when it's cooler and we don't have to do transects)
* can you find a way to direct RAs to the Dropbox field guides? They should be aware of and read the Smammal_trapping_protocol.docx, the rodent_id_cards, and the trapping_map in Dropbox.

2024-07-05 13:50 UTC, skmorgane reviewed
Everything looks really good. I left some comments on the for the Data Entry page - just some minor edits. The Portal Rodent Census instructions look good too. I am struggling with what to do about some trapping specific instructions - like putting more millet in during the winter, shutting down trapping if it rains below a certain temperature, getting out as soon as there is light during the summer to avoid heat that kills rodents and can harm people. What to do if you need to move into a hotel room due to weather/illness/whatever. Thoughts?

2024-07-05 13:50 UTC, skmorgane commented on content/docs/field-work/portal-data-entry.md
Data Entry File
- Line 36: add instructions for how to make new branch.

- Line 38: should this actually be RStudio? I'm worried someone naive or confused will see R and think they should open R directly which will then confuse them because Projects are an RStudio thing.

- Line 42: split that line to have a line instructing them how to check what branch they are working on

- Wherever we are talking about things to look at or click on in RStudo, lets change the language to RStudio
- Line 59: Put the instruction to tag GLenda before the instruction to click the button (I can already see someone getting that order wrong :) )
-

2024-07-05 13:50 UTC, skmorgane commented on content/docs/field-work/portal-data-entry.md
Portal Rodent Census Instructions look good. Do we have a separate place for things like what to do when it rains in winter or warnings about starting as early as possible in summer to avoid heat. Etc?

2024-07-05 16:06 UTC, patdumandan commented on content/docs/field-work/portal-data-entry.md
@skmorgane - I made the edits on the data entry guide. I opted not to add specifics on the trapping protocol in the rodent trip page because they're already in the small-mammal-trapping-protocol.docx file in Dropbox (@gmyenni suggested RAs get directed to that folder so they should be able to find those instructions once they get to the guides section of this page). is that okay? 

@gmyenni and @ethanwhite -- I added version tag info (major, minor, etc.) in the data entry page (pulled descriptions from Slack). are they correct?

2024-07-08 19:05 UTC, merged